version: '3'

services:
  redis:
    image: redis:latest
    container_name: garage_redis
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env